<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("title", "Фотоотчет");
$APPLICATION->SetTitle("Фотоотчет");
?><?$APPLICATION->IncludeComponent(
	"artismedia:section_galery", 
	".default", 
	array(
		"ADD_SECTIONS_CHAIN" => "Y",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "3600",
		"CACHE_TYPE" => "A",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"ELEMENT_BLOCK_SHOW_TITLE" => "Y",
		"ELEMENT_BLOCK_TITLE" => "",
		"ELEMENT_LIVE_PICTURE_RESIZE" => "Y",
		"ELEMENT_SHOW_TITLE" => "Y",
		"ELEMENT_SLIDER_AUTOPLAY" => "Y",
		"ELEMENT_SLIDER_AUTOPLAY_TIME" => "3000",
		"ELEMENT_SLIDER_COUNTER" => "(A/B)",
		"ELEMENT_SLIDER_HIDEFLASH" => "Y",
		"ELEMENT_SLIDER_LOOP" => "Y",
		"ELEMENT_SLIDER_THUMBS" => "Y",
		"ELEMENT_SLIDER_TITLE" => "Y",
		"ELEMENT_SLIDER_ZOOM" => "Y",
		"ELEMENT_SORT_FIELD" => "shows",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_TITLE_TYPE" => "UNDER",
		"IBLOCK_ID" => "17",
		"IBLOCK_TYPE" => "artismedia_section_gallery",
		"INCLUDE_JQUERY" => "Y",
		"INCLUDE_SUBSECTIONS" => "N",
		"SHOW_ALL_WO_SECTION" => "N",
		"LIST_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "",
		"PAGE_ELEMENT_COUNT" => "30",
		"SECTIONS_COUNT_ELEMENTS" => "Y",
		"SECTIONS_LIVE_PICTURE_RESIZE" => "Y",
		"SECTIONS_SHOW_PARENT_NAME" => "Y",
		"SECTIONS_SHOW_PICTURE" => "Y",
		"SECTIONS_TOP_DEPTH" => "1",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SECTION_SHOW_TITLE" => "Y",
		"SECTION_TITLE" => "",
		"SEF_MODE" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"COMPONENT_TEMPLATE" => ".default",
		"SEF_FOLDER" => "/photogallery/",
		"VARIABLE_ALIASES" => array(
			"SECTION_ID" => "SECTION_ID",
		)
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>